spring:
  # 数据库连接 
  datasource:
    username: root
    password: mysql123
    url: jdbc:mysql://localhost:3306/dev
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    host: localhost
    port: 6739
    password:
    maxTotal: 5
    maxIdle: 5
    testOnBorrow: true


# 这里配置mapper.xml的文件夹位置
mybatis:
  mapper-locations: classpath:Mappers/*Mapper.xml
  # 打开控制台输出sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
